# Note:
We will conduct three pairwise comparisons for each of the 26 crime types: pre-COVID $\rightarrow$ COVID, COVID $\rightarrow$ post-COVID, and pre-COVID $\rightarrow$ post-COVID PCA, to provide a visual representation of each era, providing a temporal trajectory map. This will allow us to see if the internal structure and relationships between the 26 crime types "stretched," "shrunk," or "rotated" as society moved through the pandemic.

In [1]:
import pandas as pd
import pyarrow as pa
import pyarrow.feather as feather
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
from sklearn.decomposition import PCA
from clusteval import clusteval
from scatterd import scatterd
from importlib.metadata import version

# python source path
sys.path.append('../Src/')
# Set seed
SEED = 1776

# custom python
import plot
import utils
import zscore_anomaly

# Create a dictionary of versions
versions = {
    "Python": sys.version.split()[0],
    "Pandas": pd.__version__,
    "NumPy": np.__version__,
    "Pyarrow": pa.__version__, 
    "Seaborn": sns.__version__,
    "Matplot": sys.modules['matplotlib'].__version__,
    "Sk-Learn": sys.modules['sklearn'].__version__,
    "Clusteval": version("clusteval"),
    "Scatterd": version("scatterd")
}

# Display as a clean DataFrame
df_versions = pd.DataFrame(list(versions.items()), columns=['Library', 'Version'])
print(df_versions)

# display all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
# Remove scientific notation
np.set_printoptions(suppress=True, precision=4, linewidth=100)
# reset options
# pd.reset_option('display.max_columns')

# Use a single Arrow string & int64 type instance to save memory
arrow_string = pd.ArrowDtype(pa.string())
arrow_int32 = pd.ArrowDtype(pa.int32())
arrow_cat8 = pd.ArrowDtype(pa.dictionary(index_type=pa.int8(), value_type=pa.string()))
arrow_cat16 = pd.ArrowDtype(pa.dictionary(index_type=pa.int16(), value_type=pa.string()))
arrow_cat32 = pd.ArrowDtype(pa.dictionary(index_type=pa.int32(), value_type=pa.string()))

     Library Version
0     Python  3.13.9
1     Pandas   2.3.3
2      NumPy   2.3.4
3    Pyarrow  22.0.0
4    Seaborn  0.13.2
5    Matplot  3.10.7
6   Sk-Learn   1.8.0
7  Clusteval   2.2.6
8   Scatterd   1.4.1

## Data Import

In [2]:
# PyArrow's version of the 'arrow' backend
df = feather.read_feather('../Data/crime_data_covid.feather', memory_map=True, types_mapper=pd.ArrowDtype)
# display
df.head()

,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,beat,district,sector,ward,community_code,community_name,community_area,fbi_code,x_coordinate,y_coordinate,year,latitude,longitude,month,day_of_week,quarter,year_quarter,time_of_day,fbi_code_desc,fbi_index_code,district_location,year_week,era,Indexed
0,01G050460,2001-01-24 20:45:00,072XX S RIDGELAND AV,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,SIDEWALK,True,False,0324,003,1,<NA>,<NA>,<NA>,<NA>,18,1189075,1857566,2001,41.764219,-87.582549,January,Wednesday,Q1,2001-Q1,Night,Drug Abuse Violations,False,Grand Crossing,2001-04,pre_covid,N
1,03J493690,2003-07-12 17:00:00,075XX S DOBSON AVE,0890,THEFT,FROM BUILDING,APARTMENT,False,False,0624,006,2,08,69,GREATER GRAND CROSSING,98853167.7093,06,1184198,1855214,2003,41.75788,-87.600498,July,Saturday,Q3,2003-Q3,Evening,Larceny – Theft,True,Gresham,2003-28,pre_covid,I
2,04X245238,2004-12-13 21:15:00,006XX N RIDGEWAY AVE,2024,NARCOTICS,POSS: HEROIN(WHITE),SIDEWALK,True,False,1122,011,4,27,23,HUMBOLDT PARK,100480876.502,18,1151273,1903996,2004,41.892451,-87.719888,December,Monday,Q4,2004-Q4,Night,Drug Abuse Violations,False,Harrison,2004-51,pre_covid,N
3,07C115980,2006-03-31 09:15:00,026XX N NARRAGANSETT AVE,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,2512,025,5,29,19,BELMONT CRAGIN,109099414.689,05,1133296,1916864,2006,41.928096,-87.78561,March,Friday,Q1,2006-Q1,Morning,Burglary,True,Grand Central,2006-13,pre_covid,I
4,07HN36467,2007-05-25 14:51:00,022XX N LA CROSSE AVE,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,RESIDENCE,True,False,2522,025,5,31,19,BELMONT CRAGIN,109099414.689,18,1143697,1914371,2007,41.921066,-87.747452,May,Friday,Q2,2007-Q2,Afternoon,Drug Abuse Violations,False,Grand Central,2007-21,pre_covid,N

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469443 entries, 0 to 8469442
Data columns (total 33 columns):
 #   Column                Dtype
---  ------                -----
 0   case_number           string[pyarrow]
 1   date                  timestamp[s][pyarrow]
 2   block                 string[pyarrow]
 3   iucr                  string[pyarrow]
 4   primary_type          string[pyarrow]
 5   description           string[pyarrow]
 6   location_description  string[pyarrow]
 7   arrest                bool[pyarrow]
 8   domestic              bool[pyarrow]
 9   beat                  string[pyarrow]
 10  district              string[pyarrow]
 11  sector                string[pyarrow]
 12  ward                  string[pyarrow]
 13  community_code        string[pyarrow]
 14  community_name        string[pyarrow]
 15  community_area        double[pyarrow]
 16  fbi_code              string[pyarrow]
 17  x_coordinate          int64[pyarrow]
 18  y_coordinate          int64[pyarrow]
 19  year                  string[pyarrow]
 20  latitude              double[pyarrow]
 21  longitude             double[pyarrow]
 22  month                 dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 23  day_of_week           dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 24  quarter               dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 25  year_quarter          string[pyarrow]
 26  time_of_day           dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 27  fbi_code_desc         dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 28  fbi_index_code        bool[pyarrow]
 29  district_location     string[pyarrow]
 30  year_week             string[pyarrow]
 31  era                   dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 32  Indexed               dictionary<values=string, indices=int8, ordered=0>[pyarrow]
dtypes: bool[pyarrow](3), dictionary<values=string, indices=int32, ordered=0>[pyarrow](6), dictionary<values=string, indices=int8, ordered=0>[pyarrow](1), double[pyarrow](3), int64[pyarrow](2), string[pyarrow](17), timestamp[s][pyarrow](1)
memory usage: 2.1 GB

## The Timeline Definition
* To ensure the analysis is accurate, we define the three eras based on global lockdown patterns:
    * Pre-COVID: January 2001 – February 2020
    * COVID Era: March 2020 – December 31, 2022
    * Post-COVID: January 2023 – Present

In [4]:
# Create the new column using .dt.strftime (Unit of Analysis: Year & Month)
df['year_month'] = df['date'].dt.strftime('%Y%m')

# convert year_month to int
df.year_month = df.year_month.astype(arrow_int32)
# check the datatype
print(df.year_month.dtype)
# display
df[['date','year_month']].head()

int32[pyarrow]

                  date  year_month
0  2001-01-24 20:45:00      200101
1  2003-07-12 17:00:00      200307
2  2004-12-13 21:15:00      200412
3  2006-03-31 09:15:00      200603
4  2007-05-25 14:51:00      200705

## Data Prep
- Which crimes share the same time‑series shape across 2001–2025, including COVID and post‑COVID structural shifts?

In [5]:
# Time & Crime Type
master_matrix = df.groupby(['year_month', 'fbi_code_desc']).size()
master_matrix.sort_index(inplace=True)

# # Replace index 'year_month' to int32
# master_matrix.index = master_matrix.index.set_levels(
#     master_matrix.index.get_level_values('year_month').astype(arrow_int32), 
#     level='year_month'
# )
# Returns a Series where the index is the level name and the value is the dtype
print(master_matrix.index.dtypes)
# Multiindex name
print(master_matrix.index.names)
print(master_matrix.index.min(), master_matrix.index.max(), "\n")

# convert this Series to a DataFrame
master_matrix_flat = master_matrix.reset_index(name="crime_count")
master_matrix_flat.head()

year_month                                                     int32[pyarrow]
fbi_code_desc    dictionary<values=string, indices=int32, ordered=0>[pyarrow]
dtype: object
['year_month', 'fbi_code_desc']
(200101, 'Aggravated Assault') (202512, 'Weapons Violations')

   year_month            fbi_code_desc  crime_count
0      200101       Aggravated Assault          546
1      200101       Aggravated Battery          967
2      200101                    Arson           67
3      200101                 Burglary         1934
4      200101  Criminal Sexual Assault          236

In [6]:
from scipy.stats import zscore

# Prevent Arrow Error
master_matrix_flat.fbi_code_desc = master_matrix_flat.fbi_code_desc.astype(str)

# Pivot
z_df_pivot = master_matrix_flat.pivot(index='fbi_code_desc', columns='year_month', values='crime_count').fillna(0)

# print shape
print("DataFrame shape:", z_df_pivot.shape, "\n")

DataFrame shape: (26, 300)

In [7]:
# Z-score each Crime Type
z_row = zscore(z_df_pivot, axis=1)
# Convert into DataFrame
z_row_df = pd.DataFrame(z_row, index=z_df_pivot.index, columns=z_df_pivot.columns)
print("Colun Names:\n", z_row_df.columns, "\n")
# Display
z_row_df.head()

Colun Names:
 Index([200101, 200102, 200103, 200104, 200105, 200106, 200107, 200108, 200109,
       200110,
       ...
       202503, 202504, 202505, 202506, 202507, 202508, 202509, 202510, 202511,
       202512],
      dtype='int32[pyarrow]', name='year_month', length=300)

year_month,200101,200102,200103,200104,200105,200106,200107,200108,200109,200110,200111,200112,200201,200202,200203,200204,200205,200206,200207,200208,200209,200210,200211,200212,200301,200302,200303,200304,200305,200306,200307,200308,200309,200310,200311,200312,200401,200402,200403,200404,200405,200406,200407,200408,200409,200410,200411,200412,200501,200502,200503,200504,200505,200506,200507,200508,200509,200510,200511,200512,200601,200602,200603,200604,200605,200606,200607,200608,200609,200610,200611,200612,200701,200702,200703,200704,200705,200706,200707,200708,200709,200710,200711,200712,200801,200802,200803,200804,200805,200806,200807,200808,200809,200810,200811,200812,200901,200902,200903,200904,200905,200906,200907,200908,200909,200910,200911,200912,201001,201002,201003,201004,201005,201006,201007,201008,201009,201010,201011,201012,201101,201102,201103,201104,201105,201106,201107,201108,201109,201110,201111,201112,201201,201202,201203,201204,201205,201206,201207,201208,201209,201210,201211,201212,201301,201302,201303,201304,201305,201306,201307,201308,201309,201310,201311,201312,201401,201402,201403,201404,201405,201406,201407,201408,201409,201410,201411,201412,201501,201502,201503,201504,201505,201506,201507,201508,201509,201510,201511,201512,201601,201602,201603,201604,201605,201606,201607,201608,201609,201610,201611,201612,201701,201702,201703,201704,201705,201706,201707,201708,201709,201710,201711,201712,201801,201802,201803,201804,201805,201806,201807,201808,201809,201810,201811,201812,201901,201902,201903,201904,201905,201906,201907,201908,201909,201910,201911,201912,202001,202002,202003,202004,202005,202006,202007,202008,202009,202010,202011,202012,202101,202102,202103,202104,202105,202106,202107,202108,202109,202110,202111,202112,202201,202202,202203,202204,202205,202206,202207,202208,202209,202210,202211,202212,202301,202302,202303,202304,202305,202306,202307,202308,202309,202310,202311,202312,202401,202402,202403,202404,202405,202406,202407,202408,202409,202410,202411,202412,202501,202502,202503,202504,202505,202506,202507,202508,202509,202510,202511,202512
fbi_code_desc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Aggravated Assault,0.190405,0.108216,1.086270,1.415027,1.357494,1.571187,2.130075,1.990353,1.719128,1.078051,0.584914,-0.097257,0.436973,-0.450672,0.724636,1.135583,1.727347,1.858850,1.932820,1.530092,1.834193,1.143802,-0.047944,0.067121,-0.105476,-0.442453,0.420536,0.363003,1.176678,1.078051,1.990353,1.513654,1.308181,1.102707,0.486287,0.132873,-0.327388,-0.097257,0.790388,0.527382,1.579406,1.793098,1.719128,1.127364,1.176678,0.913672,0.001370,-0.516423,-0.952027,-0.467110,0.223281,0.913672,1.045175,1.431465,1.299962,0.864358,0.453411,0.453411,-0.302731,-1.017778,0.132873,-0.968465,-0.105476,0.469849,0.847920,0.576695,1.283524,0.930110,0.338346,0.124654,-0.491766,-0.483547,-1.009559,-1.297222,0.239719,0.124654,0.675323,0.650666,0.880796,0.683542,0.650666,0.280814,-0.606832,-0.771210,-0.656145,-1.206814,-0.253417,0.650666,0.428755,0.749293,1.127364,0.962985,0.502725,-0.031506,-1.025997,-1.445163,-0.976684,-1.034216,0.083559,0.256157,0.280814,0.313689,0.478068,0.617790,0.017808,-0.261636,-0.721897,-1.305441,-1.297222,-1.404068,-0.615050,-0.171228,-0.039725,-0.261636,-0.163009,-0.730116,-0.245198,-0.541080,-0.804086,-1.913643,-1.469820,-1.708169,-1.075311,-0.565737,-0.360263,-0.097257,0.165749,-0.499985,-0.352044,-0.779429,-1.256128,-1.182157,-2.061583,-1.856110,-0.483547,-0.993122,-0.623269,-0.327388,-0.310950,-0.442453,-0.869838,-0.935589,-1.223252,-1.387631,-1.716388,-1.897205,-1.552009,-1.289003,-0.828743,-0.976684,-1.091749,-0.894494,-1.305441,-1.338317,-1.773921,-1.823234,-1.971175,-2.447873,-1.716388,-1.486258,-0.746553,-0.713678,-0.795867,-0.894494,-0.820524,-0.943808,-1.823234,-1.560228,-1.823234,-2.217743,-1.535571,-1.231471,-0.647926,-1.058873,-0.458891,-0.771210,-1.001341,-1.025997,-1.552009,-1.420506,-1.609542,-1.256128,-0.475329,-0.565737,0.346565,-0.031506,0.190405,0.247938,0.091778,0.058902,-0.549299,-1.058873,-0.754772,-1.330098,-0.713678,-0.261636,0.436973,0.132873,0.338346,-0.195885,0.141092,-0.146571,-0.631488,-0.968465,-0.861619,-1.198595,-0.204104,-0.401358,0.675323,0.330127,0.691761,0.124654,-0.031506,-0.080820,-0.705459,-0.573956,-0.656145,-1.231471,-0.516423,-0.245198,0.379441,0.264376,0.436973,0.067121,-0.401358,-0.228760,-0.721897,-0.705459,-0.697240,-1.108187,-0.532861,-0.968465,0.182186,1.086270,1.102707,0.806826,0.338346,0.535601,-0.319169,-0.499985,-0.442453,-0.721897,-0.047944,0.502725,0.938329,1.267086,1.538311,1.488997,1.546530,1.102707,0.363003,0.420536,-0.499985,-0.754772,0.182186,0.165749,1.423246,1.562968,1.349276,1.735566,1.045175,1.193116,0.445192,0.428755,0.289033,-0.565737,0.478068,0.856139,1.620500,1.513654,1.513654,1.579406,1.497216,1.176678,0.823264,1.045175,0.305470,0.404098,0.938329,0.913672,1.628719,1.965696,1.916382,1.710909,1.645157,1.604063,0.297252,0.075340,-0.483547,-0.861619,0.083559,0.617790,0.798607,0.913672,1.217773,0.428755,0.354784,0.141092,-0.195885,-1.404068
Aggravated Battery,0.682543,0.716008,1.489413,2.671831,2.894929,3.196111,3.672053,2.991605,2.511945,2.571437,1.690201,0.920514,0.879613,0.199164,1.344400,1.928172,2.593747,3.359716,3.396899,2.653240,2.597466,1.846370,0.504065,0.243784,-0.142919,-0.209848,0.942824,1.143612,1.381583,2.128960,2.136397,1.749694,0.909359,1.251442,0.336741,-0.187538,-0.421791,-0.194975,0.589585,0.805247,1.322090,1.664173,1.508005,1.117584,1.095274,0.704853,0.173136,-0.447819,-0.366017,-0.321397,0.139672,0.953979,1.322090,1.660455,1.816623,1.262597,0.689979,0.738317,-0.064835,-0.663480,-0.168947,-0.722973,0.277249,0.693698,1.177076,1.296062,1.734821,0.823838,0.615614,0.567276,-0.102018,-0.221003,-0.466411,-1.053902,0.585867,0.366488,1.132457,1.481977,1.400174,1.180795,1.169640,1.136175,-0.023933,-0.392045,-0.369735,-0.767593,0.158263,0.570994,1.087837,1.266315,1.429920,1.340681,0.660233,0.756909,-0.235876,-0.678354,-0.589114,-0.678354,0.366488,0.310713,0.790373,1.054373,0.857303,0.890767,0.719726,-0.075990,-0.183820,-0.708100,-0.603988,-0.923761,0.117362,0.392516,0.411107,0.537529,0.730881,0.834993,0.072742,0.143390,-0.652326,-0.946071,-0.838240,-1.373675,-0.421791,-0.128046,0.117362,0.240066,0.701134,0.158263,-0.499875,-0.064835,-0.778748,-0.827085,-1.024155,-1.321619,-0.403200,-0.682072,0.098770,0.228911,0.481755,0.095052,-0.354862,-0.499875,-0.864268,-0.946071,-1.202633,-1.589336,-0.972099,-0.953508,-0.592833,-0.284214,-0.154074,-0.325115,-0.711818,-0.860550,-1.351365,-1.291873,-1.738068,-1.712040,-1.329055,-0.860550,-0.432946,-0.302806,-0.042525,-0.462692,-0.711818,-0.693227,-1.154296,-1.061338,-1.314182,-1.708322,-0.912606,-0.737846,-0.235876,-0.418073,-0.187538,-0.161510,-0.622579,-0.618861,-1.013000,-0.931198,-0.815931,-1.221225,-0.570523,-0.659762,-0.176384,0.091334,0.180573,0.295840,-0.261904,-0.131764,-0.581678,-1.042747,-0.972099,-1.050183,-1.005564,-0.388326,-0.176384,0.087615,0.217756,-0.061116,-0.287932,-0.421791,-0.815931,-0.912606,-1.079930,-1.232380,-1.013000,-0.767593,-0.049962,-0.109454,0.206601,0.109925,-0.228440,-0.347425,-0.890297,-0.797339,-1.169169,-1.139422,-0.771311,-0.641171,-0.131764,0.031841,0.399952,-0.046243,-0.351144,-0.537058,-0.704382,-0.678354,-0.890297,-1.076211,-0.905170,-1.042747,-0.142919,0.570994,0.452009,0.544966,-0.146637,0.228911,-0.618861,-0.994409,-0.998127,-1.384830,-0.626297,-0.659762,0.020686,0.199164,0.411107,0.254939,0.206601,-0.009060,-0.622579,-0.708100,-1.053902,-1.273281,-0.815931,-0.741565,-0.306524,-0.425509,0.009531,-0.139201,-0.131764,-0.525903,-0.663480,-1.020437,-0.670917,-1.091085,-0.786184,-0.496157,-0.265623,0.016968,0.098770,-0.109454,-0.105736,-0.280496,-0.641171,-0.570523,-1.016719,-0.819649,-0.689508,-0.551932,-0.016497,0.247502,0.154545,-0.090863,-0.079708,-0.161510,-0.670917,-0.845677,-1.087366,-1.332774,-0.934916,-0.637452,-0.682072,-0.180102,-0.217285,-0.254468,-0.581678,-0.544495,-0.856832,-1.700885
Arson,0.984149,0.458522,2.350779,2.140528,2.403342,2.035403,3.980223,2.035403,1.246962,2.718718,0.931586,1.404650,2.350779,2.193091,1.982840,1.772589,1.825152,1.877715,2.035403,1.930277,2.981531,2.035403,1.089274,1.720027,0.773898,0.511085,1.246962,1.299525,2.403342,1.982840,1.877715,2.035403,2.298216,2.140528,1.825152,1.352088,1.299525,1.141837,0.984149,0.458522,0.984149,1.036712,2.035403,0.773898,0.668773,0.248271,0.668773,0.143146,-0.592732,-0.224793,0.931586,0.984149,0.248271,1.036712,1.772589,0.931586,0.668773,0.090583,0.616210,-0.592732,-0.119668,-0.172230,0.879023,0.773898,0.879023,1.457213,1.141837,0.248271,0.668773,0.248271,1.194400,0.511085,0.143146,-1.170922,1.246962,0.195708,1.141837,1.772589,1.982840,0.248271,0.616210,0.300834,0.511085,-0.014542,-0.329919,-0.487607,0.353397,0.248271,0.721335,1.089274,0.458522,1.036712,0.616210,0.511085,0.038020,-0.855545,-0.645295,-0.172230,1.089274,0.143146,0.353397,0.248271,0.668773,0.405959,0.090583,-0.119668,0.195708,-0.329919,-0.172230,-1.118359,0.038020,-0.592732,-0.224793,0.353397,0.143146,-0.014542,-0.382481,0.931586,-0.802983,-1.170922,-0.435044,-1.381172,0.090583,0.616210,-0.014542,-0.592732,-0.067105,-0.277356,-0.435044,-0.224793,-0.592732,-0.645295,-0.487607,-1.328610,-0.435044,-0.014542,-0.329919,-0.224793,-0.014542,0.405959,-0.277356,-1.013234,-1.223484,-0.855545,-0.960671,-1.433735,-0.802983,-0.960671,-0.172230,-0.750420,-0.435044,-0.645295,-1.065796,-1.381172,-1.433735,-1.276047,-1.381172,-1.118359,-1.170922,-0.855545,-0.172230,-0.329919,0.300834,-0.802983,-1.065796,-1.065796,-0.540169,-1.381172,-1.643986,-1.486298,-0.382481,-0.329919,-0.382481,-0.487607,0.143146,-0.435044,-0.487607,-0.119668,-0.172230,-0.855545,-0.329919,-0.908108,-0.382481,-0.119668,0.353397,-0.382481,-0.067105,-0.119668,-0.172230,0.143146,-0.750420,-0.592732,-0.540169,-0.435044,-1.118359,-0.067105,-0.540169,-0.119668,-0.750420,-0.277356,-0.802983,-0.487607,-0.540169,-1.433735,-1.170922,-1.801674,-0.855545,-1.118359,-0.802983,-0.645295,-0.382481,-0.540169,-0.855545,-0.645295,-1.170922,-0.855545,-1.381172,-1.013234,-1.065796,-0.908108,-1.223484,-1.013234,-0.119668,-0.645295,-1.013234,-1.065796,-0.855545,-0.382481,-1.328610,-0.908108,-1.118359,-0.645295,1.562339,1.352088,0.773898,0.458522,0.405959,0.300834,0.038020,-0.435044,-0.487607,-1.328610,0.038020,-0.382481,0.038020,0.090583,0.143146,-0.014542,-0.119668,-0.224793,-0.277356,-0.067105,-1.170922,-1.170922,-1.328610,-0.802983,-0.224793,-0.592732,-0.487607,-0.435044,0.038020,-0.382481,-1.013234,-0.697857,-0.119668,-0.802983,-1.013234,-0.592732,0.405959,0.038020,-0.172230,-0.750420,0.353397,-0.277356,-0.540169,-0.014542,-0.277356,-0.855545,-0.224793,-0.750420,-0.014542,0.038020,-0.645295,-0.067105,-0.172230,-0.382481,-0.855545,-0.960671,-0.855545,-1.013234,-0.697857,-0.487607,-1.065796,-1.013234,-0.592732,-0.697857,-1.433735,-1.223484,-0.802983,-1.328610
Burglary,0.661677,0.272703,0.513635,0.658774,0.753115,0.886644,1.481716,1.412049,1.327868,1.721197,1.401889,0.921477,0.895352,0.121758,0.352530,0.529600,0.859067,0.976630,1.407695,1.397535,1.294486,1.171117,1.191437,1.248041,0.814074,0.155140,0.674740,0.808268,0.886644,0.906963,1.095645,1.236430,1.144992,1.264007,0.914220,0.867775,0.406231,0.153688,0.576045,0.593462,0.777789,0.947602,1.227722,1.158055,1.091290,1.002755,1.053554,0.920026,0.491864,0.020160,0.442516,0.713927,1.017269,1.162409,1.330771,1.487522,1.404792,1.436723,1.043394,0.719733,0.780692,0.150786,0.570239,0.324953,1.027429,0.748761,1.156603,1.098547,0.906963,1.163860,0.742955,0.888095,0.532503,-0.201904,0.404780,0.564434,1.095645,1.010012,1.149346,1.306097,1.117416,1.316257,1.226270,0.814074,0.603621,0.118855,0.393169,0.650066,1.134832,0.988241,1.602182,1.333674,1.443980,1.673300,1.261104,1.105804,0.433808,0.107244,0.629746,0.838748,1.041943,1.240784,1.494779,1.715391,1.525258,1.510744,1.339479,1.227722,0.695059,0.001292,0.740053,0.748761,1.117416,1.129027,1.237882,1.783607,1.388827,1.462848,1.359799,0.940345,0.690705,-0.074181,0.520892,0.821331,1.438174,1.359799,1.335125,1.647175,1.503487,1.425112,1.182728,1.041943,0.404780,-0.116271,0.232064,0.243675,0.647163,0.848907,1.159506,1.078228,0.747310,0.941797,0.745858,0.478801,0.153688,-0.445738,-0.335432,-0.162716,0.123209,-0.001611,0.129015,0.423648,0.226258,0.175459,-0.000160,-0.058216,-0.495086,-0.855032,-0.615552,-0.513954,-0.394939,-0.339786,-0.117723,-0.136591,-0.258508,-0.174327,-0.497989,-0.199001,-0.599586,-1.183048,-0.915991,-0.808587,-0.585072,-0.505246,-0.466058,-0.331078,-0.431224,-0.257057,-0.377523,-0.148202,-0.429773,-0.923248,-0.624260,-0.772303,-0.540079,-0.577815,-0.187390,-0.151105,-0.155459,-0.238189,-0.148202,-0.257057,-0.296245,-0.675059,-0.794074,-0.740372,-0.605392,-0.563301,-0.394939,-0.471864,-0.635871,-0.405099,-0.573461,-0.718601,-0.763594,-1.132249,-0.950824,-0.779560,-0.730212,-0.601038,-0.489280,-0.384780,-0.618455,-0.688122,-0.820199,-0.736018,-0.987109,-1.171437,-1.162728,-1.129346,-0.962436,-1.000172,-0.798428,-0.833261,-0.875352,-0.892768,-0.995818,-0.945019,-1.071290,-1.246909,-1.320930,-1.378986,-0.225126,-1.050971,-1.074193,-0.603941,-1.252715,-1.210624,-1.246909,-1.348507,-1.439945,-1.634432,-1.573473,-1.541543,-1.460264,-1.406563,-1.338347,-1.275937,-1.175791,-1.046617,-1.081450,-1.101770,-1.304965,-1.405111,-1.306416,-1.331090,-1.267229,-1.167082,-1.129346,-1.169985,-1.194659,-1.143860,-1.165631,-1.135152,-1.161277,-1.357215,-1.318028,-1.277389,-1.254166,-1.273034,-1.223687,-1.200465,-1.216430,-1.196110,-1.156923,-1.244006,-1.342701,-1.355764,-1.286097,-1.273034,-1.037908,-1.235298,-1.039360,-1.169985,-1.110478,-1.203367,-1.300611,-1.280291,-1.358667,-1.531383,-1.492195,-1.439945,-1.425431,-1.318028,-1.291903,-1.289000,-1.403660,-1.304965,-1.471876,-1.648946
Criminal Sexual Assault,2.860974,0.341458,1.169792,0.272430,1.273334,1.480417,2.412293,1.342361,0.479513,0.859167,0.168888,-0.245279,3.930906,-0.417849,0.030832,0.755625,1.066250,1.860070,1.722015,1.549445,1.583959,1.135278,0.134374,-0.072709,2.343265,-0.486876,0.065346,-0.210765,0.548541,0.824653,0.824653,1.894584,0.617569,0.099860,0.272430,-1.073613,2.653891,0.168888,-0.624932,-0.003681,0.686597,0.962708,0.928194,1.135278,0.099860,-0.590418,-1.453266,-0.072709,2.239723,-1.246183,-0.728474,-0.590418,-0.279793,0.997222,1.273334,0.721111,1.100764,0.410486,-0.210765,-0.970071,1.722015,-1.349724,-0.486876,-0.486876,0.272430,-0.141737,2.136182,-0.624932,0.237916,0.065346,-1.142641,-1.004585,2.619377,-1.453266,-0.417849,0.410486,0.030832,0.548541,0.686597,0.168888,0.548541,0.203402,-0.832016,-0.901043,1.722015,-1.487780,-0.452362,-0.693960,-0.866530,0.617569,0.030832,0.962708,0.928194,-0.383335,-0.072709,-1.315211,1.273334,-0.935557,-0.314307,-0.797502,-0.210765,-0.107223,-0.176251,-0.003681,-0.279793,-0.935557,-1.039099,-1.246183,1.894584,-1.798405,-0.417849,-1.384238,-0.176251,-0.245279,-0.452362,-0.141737,-0.555904,-0.348821,-1.729378,-1.384238,1.411389,-1.108127,-1.108127,-0.797502,0.099860,0.375972,-0.245279,-0.279793,-0.245279,0.099860,-0.728474,-0.901043,0.962708,-1.418752,-1.073613,-0.935557,-0.107223,0.099860,0.721111,0.203402,-0.866530,-0.555904,-0.797502,-0.866530,1.204306,-1.763892,-0.728474,-1.901947,-0.624932,-0.210765,-0.141737,0.030832,-0.762988,-0.866530,-1.280697,-2.074517,0.686597,-2.212573,-1.487780,-0.659446,-0.832016,0.479513,-0.832016,0.445000,-0.314307,-0.590418,-0.314307,-1.073613,2.930002,-2.005489,-1.004585,-1.004585,-0.555904,0.962708,-0.210765,-0.176251,-0.210765,-0.417849,-1.142641,-1.211669,1.204306,-0.970071,-0.038195,-0.452362,0.652083,0.893680,0.721111,0.548541,-0.003681,0.686597,-0.521390,-1.349724,2.860974,-0.486876,-0.659446,0.686597,0.514027,-0.176251,1.342361,1.031736,0.479513,0.790139,-0.107223,-0.624932,1.376875,-0.417849,-0.038195,-0.279793,0.617569,1.480417,0.928194,1.169792,1.238820,1.100764,0.548541,0.134374,1.722015,-0.762988,-0.486876,-0.314307,1.135278,-0.003681,1.376875,0.997222,0.410486,0.341458,-0.555904,-0.555904,1.618473,-0.417849,-0.970071,-2.730281,-1.522294,-1.039099,-0.383335,-0.970071,-0.970071,-0.935557,-1.142641,-1.798405,-1.108127,-1.211669,-0.141737,-0.797502,0.203402,0.652083,0.341458,0.203402,-0.003681,-0.038195,-0.314307,-0.210765,-0.417849,-0.486876,-0.348821,0.134374,0.617569,0.306944,1.238820,0.306944,0.065346,0.928194,-0.624932,-1.246183,0.306944,-0.797502,-0.521390,-0.452362,1.031736,0.617569,0.997222,0.652083,0.237916,0.203402,0.548541,-1.211669,-0.348821,-0.417849,-0.762988,-0.555904,-0.176251,0.341458,0.168888,1.273334,0.341458,-0.693960,-0.279793,-0.486876,-0.383335,-1.349724,0.514027,0.099860,-0.141737,0.203402,0.272430,0.893680,-0.659446,0.168888,-0.901043,-2.074517